version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 289829300949.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t cicd-demo-app .
      - "docker tag cicd-demo-app:latest 289829300949.dkr.ecr.us-east-1.amazonaws.com/cicd-demo-app:latest"
      - "docker tag cicd-demo-app:latest 289829300949.dkr.ecr.us-east-1.amazonaws.com/cicd-demo-app:$CODEBUILD_RESOLVED_SOURCE_VERSION"

  post_build:
    commands:
      - "docker push 289829300949.dkr.ecr.us-east-1.amazonaws.com/cicd-demo-app:latest"
      - "docker push 289829300949.dkr.ecr.us-east-1.amazonaws.com/cicd-demo-app:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - printf '[{"name":"YOUR_CONTAINER_NAME","imageUri":"289829300949.dkr.ecr.us-east-1.amazonaws.com/cicd-demo-app:%s"}]' "$CODEBUILD_RESOLVED_SOURCE_VERSION" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
